// src/pdf/pages/Page1Cover.tsx
import React from 'react'
import { Page, View, Text, Image } from '@react-pdf/renderer'
import { pdfStyles } from '../styles/pdfStyles'
import type { ReportData } from '@/types'
import { formatDate, formatGoal, formatTrainingLevel, formatGender } from '@/lib/utils/formatters'

interface Page1CoverProps {
  data: ReportData
}

export function Page1Cover({ data }: Page1CoverProps) {
  const { member, currentAssessment, gymSettings } = data

  return (
    <Page size="A4" style={pdfStyles.page}>
      {/* Gym Branding Header */}
      <View style={pdfStyles.coverHeader}>
        {gymSettings.logoUrl && (
          <Image src={gymSettings.logoUrl} style={pdfStyles.gymLogo} />
        )}
        <Text style={[pdfStyles.gymName, { color: gymSettings.primaryColor }]}>
          {gymSettings.gymName}
        </Text>
        {gymSettings.tagline && (
          <Text style={pdfStyles.gymTagline}>{gymSettings.tagline}</Text>
        )}
      </View>

      {/* Divider Bar */}
      <View style={[pdfStyles.dividerBar, { backgroundColor: gymSettings.primaryColor }]} />

      {/* Report Title */}
      <Text style={pdfStyles.reportTitle}>Body Composition Assessment Report</Text>

      {/* Member Information Table */}
      <View style={pdfStyles.infoTable}>
        {/* Row 1 */}
        <View style={pdfStyles.infoRow}>
          <View style={pdfStyles.infoCell}>
            <Text style={pdfStyles.infoLabel}>Member Name</Text>
            <Text style={pdfStyles.infoValue}>{member.name}</Text>
          </View>
          <View style={pdfStyles.infoCellAlt}>
            <Text style={pdfStyles.infoLabel}>Member ID</Text>
            <Text style={pdfStyles.infoValue}>{member.memberId}</Text>
          </View>
          <View style={pdfStyles.infoCell}>
            <Text style={pdfStyles.infoLabel}>Age</Text>
            <Text style={pdfStyles.infoValue}>{member.age} years</Text>
          </View>
          <View style={pdfStyles.infoCellAlt}>
            <Text style={pdfStyles.infoLabel}>Gender</Text>
            <Text style={pdfStyles.infoValue}>{formatGender(member.gender)}</Text>
          </View>
        </View>

        {/* Row 2 */}
        <View style={pdfStyles.infoRow}>
          <View style={pdfStyles.infoCell}>
            <Text style={pdfStyles.infoLabel}>Height</Text>
            <Text style={pdfStyles.infoValue}>{member.height} cm</Text>
          </View>
          <View style={pdfStyles.infoCellAlt}>
            <Text style={pdfStyles.infoLabel}>Current Weight</Text>
            <Text style={pdfStyles.infoValue}>{currentAssessment.weight} kg</Text>
          </View>
          <View style={pdfStyles.infoCell}>
            <Text style={pdfStyles.infoLabel}>Assessment Date</Text>
            <Text style={pdfStyles.infoValue}>{formatDate(currentAssessment.date)}</Text>
          </View>
          <View style={pdfStyles.infoCellAlt}>
            <Text style={pdfStyles.infoLabel}>Total Assessments</Text>
            <Text style={pdfStyles.infoValue}>{member.assessments.length}</Text>
          </View>
        </View>

        {/* Row 3 */}
        <View style={pdfStyles.infoRowLast}>
          <View style={pdfStyles.infoCell}>
            <Text style={pdfStyles.infoLabel}>Goal</Text>
            <Text style={pdfStyles.infoValue}>{formatGoal(member.goal)}</Text>
          </View>
          <View style={pdfStyles.infoCellAlt}>
            <Text style={pdfStyles.infoLabel}>Training Level</Text>
            <Text style={pdfStyles.infoValue}>{formatTrainingLevel(member.trainingLevel)}</Text>
          </View>
          <View style={pdfStyles.infoCell}>
            <Text style={pdfStyles.infoLabel}>Member Since</Text>
            <Text style={pdfStyles.infoValue}>{formatDate(member.joinDate)}</Text>
          </View>
          <View style={pdfStyles.infoCellAlt}>
            <Text style={pdfStyles.infoLabel}>Report Generated</Text>
            <Text style={pdfStyles.infoValue}>{formatDate(new Date())}</Text>
          </View>
        </View>
      </View>

      {/* Optional notes */}
      {currentAssessment.notes && (
        <View style={{ backgroundColor: '#f9fafb', borderRadius: 8, padding: 12, marginTop: 8 }}>
          <Text style={{ fontSize: 9, color: '#6b7280', marginBottom: 4, textTransform: 'uppercase' }}>
            Trainer Notes
          </Text>
          <Text style={{ fontSize: 10, color: '#374151', lineHeight: 1.5 }}>
            {currentAssessment.notes}
          </Text>
        </View>
      )}

      {/* Footer */}
      <View style={pdfStyles.footer}>
        <Text style={pdfStyles.footerText}>
          {gymSettings.address || ''} {gymSettings.phone ? `• ${gymSettings.phone}` : ''}
        </Text>
        <Text style={pdfStyles.footerBrand}>Generated by FitnessTouch</Text>
      </View>
    </Page>
  )
}
